### ISSUE TITLE
master does not compile

### ISSUE THREAD

**Issue by gaul** [jenkinsci/lib-file-leak-detector#23]
When running `mvn test`:

```
[ERROR] COMPILATION ERROR :
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[8,24] package org.kohsuke.asm3 does not 
exist
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[9,29] package org.kohsuke.asm3.util does
 not exist
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[45,38] cannot find symbol
  symbol:   class ClassReader
  location: class org.kohsuke.file_leak_detector.TransformerTest
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[45,9] cannot find symbol
  symbol:   variable CheckClassAdapter
  location: class org.kohsuke.file_leak_detector.TransformerTest
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project file-leak-detector: Compilation failure: Compilation failure:
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[8,24] package org.kohsuke.asm3 does not exist
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[9,29] package org.kohsuke.asm3.util does not exist
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[45,38] cannot find symbol
[ERROR] symbol:   class ClassReader
[ERROR] location: class org.kohsuke.file_leak_detector.TransformerTest
[ERROR] /home/gaul/work/file-leak-detector/src/test/java/org/kohsuke/file_leak_detector/TransformerTest.java:[45,9] cannot find symbol
[ERROR] symbol:   variable CheckClassAdapter
[ERROR] location: class org.kohsuke.file_leak_detector.TransformerTest
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Reverting 1ddd4dc5fd81a65422e90ba04960be8a8516d8ed works around this.

**Comment by centic9** [comment]
This is the same as PR #22

**Comment by basil** [comment]
Fixed in #22.
